# -*- coding: utf-8 -*-
"""covid 19

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J54SCCs3HVIh00KQ8RuwqwfUCPc-Y9ui
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the 'sales.csv' file into a DataFrame named 'df' to resolve the NameError.
# Ensure that 'sales.csv' has been generated by the previous cell before running this.
df = pd.read_csv('sales.csv')

import pandas as pd
import numpy as np

data = {
    'Date': pd.to_datetime(pd.date_range(start='2023-01-01', periods=100, freq='D')),
    'Store': np.random.choice([f'Store_{i}' for i in range(1, 11)], 100),
    'Item': np.random.choice([f'Item_{i}' for i in range(1, 21)], 100),
    'Sales': np.random.randint(100, 1000, 100)
}
dummy_df = pd.DataFrame(data)
dummy_df.to_csv('sales.csv', index=False)

print("Generated a dummy 'sales.csv' file.")

print("First 5 Rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

df['Date'] = pd.to_datetime(df['Date'])

print("\nMissing Values:")
print(df.isnull().sum())

df = df.drop_duplicates()

print("\nStatistics:")
print(df['Sales'].describe())

total_sales = df['Sales'].sum()
avg_sales = df['Sales'].mean()
max_sales = df['Sales'].max()
min_sales = df['Sales'].min()

print("\nTotal Sales:", total_sales)
print("Average Sales:", avg_sales)
print("Max Sales:", max_sales)
print("Min Sales:", min_sales)

plt.figure()
df.groupby('Date')['Sales'].sum().plot()
plt.title("Sales Trend Over Time")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()